version: '3.4'
services:
  frens.avado.dappnode.eth:
    build: ./build
    image: 'frens.avado.dappnode.eth:0.0.1'
    restart: always
    volumes:
      - 'data:/data'
    ports:
      - '80:80'
volumes:
  data: {}
